#!/bin/bash
# Script per aiutare nella cattura degli screenshot
# Questo script apre VSCode e fornisce istruzioni passo-passo

echo "=========================================="
echo "Git File History - Screenshot Helper"
echo "=========================================="
echo ""
echo "Questo script ti guiderà nella cattura degli screenshot."
echo ""
echo "Requisiti:"
echo "1. Avere un repository Git con almeno 5-10 commit"
echo "2. Avere un file con storia di commit"
echo "3. Estensione Git File History installata"
echo ""
read -p "Premi INVIO per continuare..."

echo ""
echo "=== SCREENSHOT 1: File History Sidebar ==="
echo "1. Apri VSCode/Cursor"
echo "2. Apri un file nel progetto"
echo "3. Click destro sul file → 'Show FZ Git History'"
echo "4. Espandi la sezione 'Git File History' nella sidebar"
echo "5. Cattura screenshot: screenshots/screenshot-file-history-sidebar.png"
read -p "Premi INVIO quando hai completato..."

echo ""
echo "=== SCREENSHOT 2: Git Blame Annotations ==="
echo "1. Apri un file con codice sorgente"
echo "2. Click destro nell'editor → 'Toggle Git Blame'"
echo "3. Attendi che appaiano le annotazioni"
echo "4. Cattura screenshot: screenshots/screenshot-git-blame-annotations.png"
read -p "Premi INVIO quando hai completato..."

echo ""
echo "=== SCREENSHOT 3: Diff Viewer ==="
echo "1. Click destro su un file → 'Compare with Previous Commit'"
echo "2. Cattura il diff viewer aperto"
echo "3. Cattura screenshot: screenshots/screenshot-diff-viewer.png"
read -p "Premi INVIO quando hai completato..."

echo ""
echo "=== SCREENSHOT 4: Context Menu ==="
echo "1. Click destro su un file nell'Explorer (non nell'editor)"
echo "2. Cattura il menu contestuale"
echo "3. Cattura screenshot: screenshots/screenshot-context-menu.png"
read -p "Premi INVIO quando hai completato..."

echo ""
echo "=== SCREENSHOT 5: Commit Details View ==="
echo "1. Nella File History view, clicca su un commit"
echo "2. Cattura l'editor con il file storico aperto"
echo "3. Cattura screenshot: screenshots/screenshot-commit-details-view.png"
read -p "Premi INVIO quando hai completato..."

echo ""
echo "=== SCREENSHOT 6: Compare Dialog ==="
echo "1. Click destro su un file → 'Compare Two Commits'"
echo "2. Cattura il Quick Pick dialog"
echo "3. Cattura screenshot: screenshots/screenshot-compare-dialog.png"
read -p "Premi INVIO quando hai completato..."

echo ""
echo "=========================================="
echo "Completato! Verifica che tutti gli screenshot siano nella cartella screenshots/"
echo "=========================================="
